name: "Build and Release"
on:
  pull_request:
  push:
    tags:
      - "v*"
    branches: 
      - "CI/Release"
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v16
      with:
        name: nixarkye03
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # - run: nix flake check
    - run: nix build .#all-tarballs
    - uses: ncipollo/release-action@v1.18.0
      with:
        tag: ${{ github.ref_name != 'CI/Release' && github.ref_name || format('test-{0}', github.run_number) }}
        prerelease: true
        artifactErrorsFailBuild: true
        artifacts: "result/*"